version: "3"

services:
    app:
        build:
            context: .
        volumes:
            - ".:/home"
        hostname: projeto
        user: 1000:100
        ports:
            - "8000:8000"
        environment:
            - PYTHONPATH=/home
        depends_on:
            - postgres
    postgres:
        build:
            context: .
            dockerfile: "Dockerfile-pgsql"
        environment:
            - POSTGRES_PASSWORD=Fuck0ff
            - DB_NAME=projeto
            - DB_USER_NAME=projeto
            - DB_PASSWORD=123123
        hostname: postgres
        volumes:
            - pgsql_13_vol:/var/lib/postgresql/data
        ports:
            - "5432:5432"
volumes:
    pgsql_13_vol:
