#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE $DB_USER_NAME WITH PASSWORD '$DB_PASSWORD' CREATEROLE CREATEDB LOGIN;
    CREATE DATABASE $DB_NAME OWNER $DB_USER_NAME ENCODING = UTF8;
EOSQL
